---
name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '⬆️ Dependency Updates'
    label: 'dependencies'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '.github/*'
  - label: 'bug'
    title:
      - '/fix/i'
  - label: 'dependencies'
    files:
      - 'uv.lock'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'chore'
      - 'dependencies'
      - 'bug'
  default: patch
template: |
  # Changes

  $CHANGES

  ## Contributors
  We'd like to thank all the contributors who worked on this release!

  $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
