version: 2
build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
    post_install:
      - poetry config virtualenvs.create false
      - poetry install

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt