---

name: Generate and publish documentation

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish_documentation:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fakeredis
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7
        with:
          python-version: "3.14"
      - name: Publish documentation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          pip install --group 'documentation'
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force --verbose
          mkdocs --version
