---
name: Unit tests

on:
  push:
    branches:
      - master
    paths:
      - 'fakeredis/**'
      - 'test/**'
      - '.github/workflows/test.yml'
      - '.github/workflows/test-combination.yml'
      - 'pyproject.toml'
  pull_request:
    branches:
      - master
    paths:
      - 'fakeredis/**'
      - 'test/**'
      - '.github/workflows/test.yml'
      - '.github/workflows/test-combination.yml'
      - 'pyproject.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    uses: ./.github/workflows/lint.yml
  basic_tests:
    needs: ["ruff"]
    name: Tests without server
    uses: ./.github/workflows/test-no-matrix.yml
  test:
    needs: ["ruff", "basic_tests"]
    strategy:
      max-parallel: 8
      fail-fast: false
      matrix:
        server-image:
          - "redis:8.8"
          - "valkey/valkey:9.1"
          - "redis:7.4.8"
          - "valkey/valkey:8.1.8"
          - "redis:6.2.17"
        python-version: ["3.10", "3.12", "3.13", "3.14"]
        redis-py: ["4.6.0", "6.4.0", "7.4.0", "8.1.0"]
        install-extras: [false]
        coverage: [false]
        exclude:
          - python-version: "3.10"
            redis-py: "7.4.0"
          - python-version: "3.10"
            redis-py: "8.1.0"
          - python-version: "3.14"
            server-image: "redis:8.8"
            redis-py: "7.4.0"
            install-extras: false
            coverage: false
        include:
          - python-version: "3.10"
            server-image: "redis:8.8"
            redis-py: "4.6.0"
            install-extras: false
            coverage: false
          - python-version: "3.10"
            server-image: "redis:8.8"
            redis-py: "5.3.1"
            install-extras: false
            coverage: false
          - python-version: "3.14"
            server-image: "redis/redis-stack-server:6.2.6-v20"
            redis-py: "8.1.0"
            install-extras: true
            coverage: false
          - python-version: "3.14"
            server-image: "redis/redis-stack-server:7.4.0-v8"
            redis-py: "8.1.0"
            install-extras: true
            coverage: false
          - python-version: "3.14"
            server-image: "redis:8.8"
            redis-py: "8.1.0"
            install-extras: true
            coverage: true
          - python-version: "3.14"
            server-image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.40.2"
            redis-py: "8.1.0"
            install-extras: true
            coverage: false
    permissions:
      contents: read
      pull-requests: write
    name: >
      tests
      ${{ matrix.server-image }},
      py${{ matrix.python-version }},redis-py:${{ matrix.redis-py }},
      cov:${{ matrix.coverage }},extra:${{matrix.install-extras}}
    uses: ./.github/workflows/test-combination.yml
    with:
      server-image: ${{ matrix.server-image }}
      python-version: ${{ matrix.python-version }}
      redis-py: ${{ matrix.redis-py }}
      install-extras: ${{ matrix.install-extras }}
      coverage: ${{ matrix.coverage }}
      timeout-minutes: 5
    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
